#!/bin/bash

read -p "Realiser le suivi du commit ? [y/n]" yn < /dev/tty
yn=${yn:-n}

case $yn in
[Yy]* )

	mkdir -p suivi
	echo "Commit verifie le $(date '+%Y-%m-%d %H:%M:%S')" > suivi/commitInfo.txt
	git add suivi/commitInfo.txt
	exit 0
	;;
[Nn]* )

	exit 0
	;;
* )

	exit 0
	;;
esac

exit 0